class Classes {
  static final String HEADER = 'header';
  static final String CONTAINER = 'container';
  static final String CONTAINER_EXPANDED = 'containerExpanded';
  static final String CONTAINER_COLLAPSED = 'containerCollapsed';
  static final String MONTH = 'month';
  static final String MONTH_HEADER = 'monthHeader';
  static final String MONTH_NAME = 'monthName';
  static final String YEAR = 'year';
  static final String FLOAT_RIGHT = 'floatRight';
  static final String EXPANDER = 'expander';
  static final String CONTENT = 'content';
  static final String DAYS = 'days';
  static final String DAY = 'day';
  static final String DAY_HEADER = 'dayHeader';
  static final String DAY_DATE = 'dayDate';
  static final String HOURS_WORKED = 'hoursWorked';
  static final String HOURS_TO_WORK = 'hoursToWork';
  static final String TIME_ENTRIES = 'timeEntries';
  static final String TIME_ENTRY = 'timeEntry';
  static final String TIME_ENTRY_EDIT = 'timeEntryEdit';
  static final String TIME_ENTRY_VIEW = 'timeEntryView';
  static final String TIME = 'time';
  static final String TIME_SEPARATOR = 'timeSeparator';
  static final String ENTRY_TIME_FROM = 'entryTimeFrom';
  static final String ENTRY_TIME_TO = 'entryTimeTo';
  static final String PROJECT = 'project';
  static final String ACTIVITY = 'activity';
  static final String COMMENT = 'comment';
  static final String MODALIFIER = 'modalifier';
  static final String DIALOG = 'dialog';
  static final String DIALOG_TEXT = 'dialogText';
  static final String DIALOG_BUTTON_BAR = 'dialogButtonBar';
  static final String DIALOG_CANCEL_BUTTON = 'dialogCancelButton';
  static final String DIALOG_OK_BUTTON = 'dialogOkButton';
  static final String MODALIFIED = 'modalified';
  static final String ADD_ENTRY_SECTION = 'addEntrySection';
  static final String ADD_ENTRY_BUTTON = 'addEntryButton';

  Classes.internal();
}
