class WebServiceRequesterMock extends Mock implements WebServiceRequester {}
class ErrorDisplayMock extends Mock implements ErrorDisplay {}
class ActivityRepositoryMock extends Mock implements ActivityRepository {}
class TimeEntryRepositoryMock extends Mock implements TimeEntryRepository {}
class DayDisplayViewMock extends Mock implements DayDisplayView {}
class DayDisplayModelMock extends Mock implements DayDisplayModel {}
class TimeEntryEditorFactoryMock extends Mock implements TimeEntryEditorFactory {}
class ElementMock extends Mock implements Element {}
class TimeEntryEditorMock extends Mock implements TimeEntryEditor {}
